In [18]:
import pandas as pd
import numpy as np
import glob, os

In [48]:
def read_files(root, mouse):
    os.chdir(root)
    csv_files = glob.glob('*.csv')
    csv_files = sorted(list(csv_files))
    
    # only includes data csv files named based on starting second to ending second naming system
    # does not remerge finished csv with original data files if this is run twice
    csv_files = [f for f in csv_files if f[:1].isdigit()]
    
    global data
    data = pd.DataFrame()

    i=0
    last_ts = 0
    last_frame = 0
    for f in csv_files:
        df = pd.read_csv(f)
        df, last_ts, last_frame = adjust_indices(df, last_ts, last_frame)
        df.insert(0, "Interval", len(df.index.values)*["Clip " + str(i+1) + ": " + str(f)][:3])
        data = pd.concat([data, df])
        i += 1
        
    data.index = pd.Index(range(len(data.index)))

def adjust_indices(df, ts, frame):
    df.loc[:, "Frame Index"] = df.loc[:, "Frame Index"].values + frame
    df.loc[:, "Timestamp(x)"] = df.loc[:, "Timestamp(x)"].values + ts
    return df, ts+30, frame+7200

def save_full_csv(root, mouse):
    os.chdir(root)
    output = mouse + '.csv'
    data.to_csv(output)
    
def save_ctrl_vs_treated(root, mouse, st, click):
    os.chdir(root)
    before = mouse + '_control.csv'
    after = mouse + '_treated.csv'
    st = float(str(st).zfill(3))
    click = float(str(click).zfill(3))
    ctrl = data.loc[data["Timestamp(x)"] <= st] # split across before and after
    treated = data.loc[data["Timestamp(x)"] >= click]
    ctrl.to_csv(before)
    treated.to_csv(after)
    
    
def save_ctrl_vs_treated2(root, mouse, vid1, frame_st, vid2, frame_click,):
    """
        Alternate helper method which reads in user friendly inputs. Get index numbers
        and starting times of filenames from PainFace.
    """
    os.chdir(root)
    before = mouse + '_control.csv'
    after = mouse + '_treated.csv'
    #vid1 = 
    ctrl = data.loc[data["Frame Index"] <= frame_st+vid1*240] # split across before and after
    treated = data.loc[data["Timestamp(x)"] >= after]
    ctrl.to_csv(before)
    treated.to_csv(after)

cwd = os.getcwd()
print(cwd)
read_files(cwd, 'MOUSE_A')
save_full_csv(cwd, 'MOUSE_A')
save_ctrl_vs_treated(cwd, 'MOUSE_A', 170, 240)
data

/Users/sense_imac3/Documents/GitHub/cv-for-nasal-pain-assay/MOUSE_A


Interval Subject Type  Frame Index  Timestamp(x)  Orbital  Nose  \
0     Clip 1: 000.csv      c57bl/6            0         0.000        1    -1   
1     Clip 1: 000.csv      c57bl/6          240         1.001        1    -1   
2     Clip 1: 000.csv      c57bl/6          480         2.002        2     2   
3     Clip 1: 000.csv      c57bl/6          720         3.003       -1    -1   
4     Clip 1: 000.csv      c57bl/6          960         4.004       -1     2   
..                ...          ...          ...           ...      ...   ...   
892  Clip 30: 870.csv      c57bl/6       214080       892.022        0    -1   
893  Clip 30: 870.csv      c57bl/6       214320       893.023       -1    -1   
894  Clip 30: 870.csv      c57bl/6       214560       894.024       -1    -1   
895  Clip 30: 870.csv      c57bl/6       214800       895.025       -1    -1   
896  Clip 30: 870.csv      c57bl/6       215040       896.026        1     0   

     Ears  Whiskers  Cheek  Total Grimace Score  AU Scored  \
0       2        -1    NaN                  NaN          2   
1       2        -1    NaN                  NaN          2   
2       1        -1    NaN                  NaN          3   
3      -1        -1    NaN                  NaN          0   
4       1        -1    NaN                  NaN          2   
..    ...       ...    ...                  ...        ...   
892     2        -1    NaN                  NaN          2   
893     1        -1    NaN                  NaN          1   
894    -1        -1    NaN                  NaN          0   
895    -1        -1    NaN                  NaN          0   
896     2        -1    NaN                  NaN          3   

     Confidence(Orbital)  Confidence(Nose)  Confidence(Ears)  \
0               0.764252          0.000000          0.999628   
1               0.746516          0.000000          0.999971   
2               0.823970          0.997830          0.999010   
3               0.000000          0.000000          0.000000   
4               0.000000          0.815368          0.999997   
..                   ...               ...               ...   
892             0.999509          0.000000          0.999920   
893             0.000000          0.000000          0.996046   
894             0.000000          0.000000          0.000000   
895             0.000000          0.000000          0.000000   
896             0.999998          0.999996          0.999786   

     Confidence(Whiskers)  Confidence(Cheek)             Face Model  \
0                     0.0                NaN  general/fau/generalv5   
1                     0.0                NaN  general/fau/generalv5   
2                     0.0                NaN  general/fau/generalv5   
3                     0.0                NaN  general/fau/generalv5   
4                     0.0                NaN  general/fau/generalv5   
..                    ...                ...                    ...   
892                   0.0                NaN  general/fau/generalv5   
893                   0.0                NaN  general/fau/generalv5   
894                   0.0                NaN  general/fau/generalv5   
895                   0.0                NaN  general/fau/generalv5   
896                   0.0                NaN  general/fau/generalv5   

                    MGS Model  
0    c57bl6-pain-mgs-20220901  
1    c57bl6-pain-mgs-20220901  
2    c57bl6-pain-mgs-20220901  
3    c57bl6-pain-mgs-20220901  
4    c57bl6-pain-mgs-20220901  
..                        ...  
892  c57bl6-pain-mgs-20220901  
893  c57bl6-pain-mgs-20220901  
894  c57bl6-pain-mgs-20220901  
895  c57bl6-pain-mgs-20220901  
896  c57bl6-pain-mgs-20220901  

[897 rows x 18 columns]

In [15]:
data
len(data.index)

897

In [245]:
FAU_NAMES = data.columns[3:7]
CONF_NAMES = data.columns[10:14]

# have user input viable indices where bounding boxes are accurate
viables = [11, 24, 25]
faus = data.loc[viables, FAU_NAMES]
fau_arr = np.asarray(faus)
confs = data.loc[viables, CONF_NAMES]
conf_arr = np.asarray(confs)

clean_data = faus.join(confs)
clean_data

Timestamp(x)  Orbital  Nose  Ears  AU Scored  Confidence(Orbital)  \
11        11.011       -1    -1    -1          0             0.000000   
24        24.024        0     2     2          3             0.998753   
25        25.025        1     0     1          3             0.998814   

    Confidence(Nose)  Confidence(Ears)  
11          0.000000          0.000000  
24          0.991525          0.999983  
25          0.788076          1.000000

In [13]:
fau_arr
conf_arr

array([[3.        , 0.99990129, 0.        , 0.99804413],
       [2.        , 0.90824449, 0.        , 0.56698865],
       [3.        , 0.99999976, 0.        , 0.99974674]])

In [15]:
def get_all_fau_scores(data):
    """
        Get data per FAU without filtering for manually confirmed bounding box accuracy.
        Run the same analytics as with clean data on all timestamps of the data matrix without checking
        whether the bounding boxes were correctly identified at those points.
    """
    
    THRESHOLD = 0.90
    
    faus = {}
    fs_sorted = {}
    times = {}
    
    for i in range(len(FAU_NAMES)):
        fau = FAU_NAMES[i]
        conf = CONF_NAMES[i]
        
        mgs = data[fau].where(data[conf] >= THRESHOLD).dropna()
        mgs_sorted = data.sort_values(conf, ascending=False)[fau]
        sorted_arrs = np.asarray(mgs_sorted)
        print(mgs)
        #print(mgs_sorted, "\n")
        faus[fau] = np.asarray(mgs)
        print("index", mgs.index, "\n")
        times[fau] = mgs.index
        fs_sorted[fau] = sorted_arrs
    
    return faus, times, fs_sorted

def get_clean_fau_analytics():
    """
        Get clean data per FAU after filtering for high confidence scores only.
        
        For each Facial Action Unit, filter for datapoints that correspond to high confidence values.
        
        Returns 3 dictionaries with:
            - Faus: data arrays with all high confidence scores organized by FAU identity
            - Times: label arrays containing timestamp identity for each included confidence score per FAU
            - Scores sorted: dataframes containing all FAU scores sorted by confidence across each individual column
    """
    THRESHOLD = 0.90
    
    faus = {}
    fs_sorted = {}
    times = {}
    
    for i in range(len(FAU_NAMES)):
        fau = FAU_NAMES[i]
        conf = CONF_NAMES[i]
        
        mgs = clean_data[fau].where(clean_data[conf] >= THRESHOLD).dropna()
        mgs_sorted = clean_data.sort_values(conf, ascending=False)[fau]
        sorted_arrs = np.asarray(mgs_sorted)
        faus[fau] = np.asarray(mgs)
        times[fau] = mgs.index
        fs_sorted[fau] = sorted_arrs
    
    return faus, times, fs_sorted

def display_analytics_report(faus, times, fs_sorted):
    # user friendly report:
    
    tstamps = {}
    [tstamps.update({k:np.asarray(data.loc[times[k], "Timestamp(x)"])}) for k in times.keys()]
    
    print("*** COMPLETED FAU ANALYTICS ON CLEAN DATAFRAME ***\n\n")
    
    for fau in faus.keys():
        print("\n\n**", fau, "**\n\n")
        print("For", fau, "Facial Action Unit:\n")
        print("High confidence Mouse Grimace Scale scores for this clip:\n", faus[fau])
        print("\nCorresponding timestamps for high confidence MGS score:\n", tstamps[fau])
        print("\nAll viable Mouse Grimace Scale scores descending order of Confidence Score:\n", fs_sorted[fau])
    

def get_fau_scores(viables, fau, conf):
    """
        Get arrays of Facial Action Unit scores across each row of data that has been determined to be viable through visual inspection.
        IGNORE. not pursuing this anymore.
    """
    THRESHOLD = 0.90
    
    fau_mgs = {}
    for fau in FAU_NAMES:
        fau_mgs[str(fau)] = []
    
    for v in range(len(viables)):
        for fi in range(len(fau)):
            if conf[v][fi] >= THRESHOLD:
                pass
                #print(fau_mgs[list(fau_mgs.keys())[fi]], fau[v][fi])
                #fau_mgs[list(fau_mgs.keys())[fi]].append(fau[v][fi])
    
    print(fau_mgs)
    return NotImplemented



f,t,s = get_clean_fau_analytics()
display_analytics_report(f,t,s)

*** COMPLETED FAU ANALYTICS ON CLEAN DATAFRAME ***




** Timestamp(x) **


For Timestamp(x) Facial Action Unit:

High confidence Mouse Grimace Scale scores for this clip:
 [11.011 24.024 25.025]

Corresponding timestamps for high confidence MGS score:
 [11.011 24.024 25.025]

All viable Mouse Grimace Scale scores descending order of Confidence Score:
 [11.011 25.025 24.024]


** Orbital **


For Orbital Facial Action Unit:

High confidence Mouse Grimace Scale scores for this clip:
 [0 0 1]

Corresponding timestamps for high confidence MGS score:
 [11.011 24.024 25.025]

All viable Mouse Grimace Scale scores descending order of Confidence Score:
 [1 0 0]


** Nose **


For Nose Facial Action Unit:

High confidence Mouse Grimace Scale scores for this clip:
 []

Corresponding timestamps for high confidence MGS score:
 []

All viable Mouse Grimace Scale scores descending order of Confidence Score:
 [-1 -1 -1]


** Ears **


For Ears Facial Action Unit:

High confidence Mouse Grimace Scale

In [16]:
def get_clean_rows(temp):
    """
        Get clean data per row after filtering for high confidence rows only.
        
        Filter for rows that correspond to high average confidence value across Facial Action Units.
        Returns a dictionary with viable FAU scores at timepoints of accurate bounding box classification and high confidence scores across facial action units.
    """
    THRESHOLD = 0.90
    
    # insert new column with average confidence value
    if "Avg Confidence" in temp.columns.values:
        temp = temp.drop(columns=['Avg Confidence'])
    temp.insert(len(temp.columns), "Avg Confidence", np.mean(np.asarray(temp.loc[:, CONF_NAMES]), axis=1))
    filtered = temp.sort_values(by='Avg Confidence', ascending=False)
    fau = filtered.loc[:, FAU_NAMES]
    conf = filtered.loc[:, CONF_NAMES]
    avg = filtered.loc[:, 'Avg Confidence']
    filtered = fau.join(avg)
    # join confidence columns as well
    #filtered = fau.join(avg).join(conf)
    
    return filtered
    
get_clean_rows(data)

Timestamp(x)  Orbital  Nose  Ears  Avg Confidence
28        28.028        0     0     2        1.749410
52        52.022        1     0     0        1.745738
38        38.008        1     2     2        1.745405
53        53.023        1     0     0        1.720748
49        49.019        1     0     0        1.715644
56        56.026        1     0     0        1.639012
30        30.000        0     2     0        1.499948
46        46.016        0     0     2        1.499862
54        54.024        1     0     1        1.483923
50        50.020        1     2     1        1.343722
48        48.018        0     2     2        1.295977
25        25.025        1    -1     1        1.249937
12        12.012        1    -1     1        1.249638
11        11.011        0    -1     0        1.249486
57        57.027        0    -1     0        1.248255
19        19.019        2    -1     2        1.246182
23        23.023        1    -1     1        1.228748
26        26.026       -1     0     2        1.224128
47        47.017        1    -1     0        1.173388
16        16.016        1    -1     2        1.167058
29        29.029        1    -1     2        1.132746
32        32.002        1    -1     1        1.129671
21        21.021       -1     2     2        1.127700
55        55.025        0     0    -1        0.999940
41        41.011        1     2    -1        0.999936
43        43.013        1    -1     1        0.999698
1          1.001        1     2    -1        0.999513
17        17.017        2    -1     1        0.999428
13        13.013        1    -1     2        0.999255
2          2.002        2    -1     1        0.998104
27        27.027        1    -1     2        0.995389
45        45.015        1    -1     1        0.993923
35        35.005       -1     0     1        0.987073
34        34.004        0    -1     2        0.985982
33        33.003        2    -1     1        0.982949
20        20.020        1    -1     2        0.976719
4          4.004        2    -1     1        0.947798
5          5.005        2    -1     1        0.946923
51        51.021        1     0    -1        0.906490
14        14.014        1    -1     2        0.885399
24        24.024        0    -1     1        0.868808
15        15.015       -1    -1     2        0.749996
18        18.018       -1    -1     1        0.748731
31        31.001       -1    -1     2        0.748440
10        10.010       -1    -1     1        0.499999
39        39.009       -1    -1     1        0.499968
3          3.003        1    -1    -1        0.499201
40        40.010       -1     0    -1        0.499155
59        59.029       -1    -1     2        0.497596
7          7.007       -1    -1     1        0.496134
22        22.022       -1    -1     1        0.483762
44        44.014       -1    -1    -1        0.000000
42        42.012       -1    -1    -1        0.000000
37        37.007       -1    -1    -1        0.000000
36        36.006       -1    -1    -1        0.000000
9          9.009       -1    -1    -1        0.000000
8          8.008       -1    -1    -1        0.000000
6          6.006       -1    -1    -1        0.000000
58        58.028       -1    -1    -1        0.000000
0          0.000       -1    -1    -1        0.000000